#just for tac
statistics=true
job=J_Master_ETL
jobVersion=0.1
date=2026-04-01 154145382
contextName=Docker
jobId=_vZnZ4CLOEfGRxqel4Yypgg
jobType=Standard
framework=
projectId=0
applyContextToChildren=true
project=DWH_ATTEJARIBANK
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=